# Generated by Django 5.1.1 on 2025-08-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
